name:       hnix
version:    0.5.0
synopsis:   Haskell implementation of the Nix language
github:     jwiegley/hnix
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System, Data, Nix
license:    BSD3

description:
  Haskell implementation of the Nix language.

extra-source-files:
  - README.md

dependencies:
  - base                        >= 4.9 && < 5
  - ansi-wl-pprint
  - bytestring
  - compact
  - containers
  - data-fix
  - deepseq
  - exceptions
  - filepath
  - mtl
  - optparse-applicative
  - serialise
  - template-haskell
  - text
  - transformers
  - unordered-containers        >= 0.2.9 && < 0.3

ghc-options:
  - -Wall

flags:
  tracing:
    description: Enable full debug tracing
    manual: True
    default: False

  optimize:
    description: Enable all optimization flags
    manual: True
    default: False

when:
  - condition: flag(optimize)
    ghc-options:
      - -fexpose-all-unfoldings
      - -fspecialise-aggressively
      - -O2

when:
  - condition: flag(tracing)
    cpp-options: -DENABLE_TRACING=1

library:
  source-dirs: src
  dependencies:
    - aeson
    - ansi-wl-pprint
    - array                     >= 0.4 && < 0.6
    - base16-bytestring
    - binary
    - cryptohash
    - deriving-compat           >= 0.3 && < 0.5
    - directory
    - ghc-datasize
    - hashable
    - haskeline
    - megaparsec
    - monadlist
    - pretty-show
    - process
    - regex-tdfa
    - regex-tdfa-text
    - scientific
    - semigroups                >= 0.18 && < 0.19
    - split
    - syb
    - these
    - unix
    - vector
    - xml

executables:
  hnix:
    source-dirs: main
    main: Main.hs
    dependencies:
      - hnix
      - aeson
      - repline
      - haskeline

tests:
  hnix-tests:
    source-dirs: tests
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - hnix
      - Glob
      - directory
      - interpolate
      - process
      - split
      - tasty
      - tasty-hunit
      - tasty-th
      - unix

benchmarks:
  hnix-benchmarks:
    source-dirs: benchmarks
    main: Main.hs
    dependencies:
      - hnix
      - criterion
